apiVersion: apps/v1
kind: Deployment
metadata:
  name: server--discovery-stack-deployment
  namespace: shoes-eks
spec:
  selector:
    matchLabels:
      app: server--discovery-stack
  template: 
    metadata:
        name: server--discovery-stack
        labels:
          app: server--discovery-stack
    spec:
        containers:
          - name: server--discovery-stack-container
            image: $dck-accountid/$dck-repository:server--discovery-stack-$githash
            env:
              - name: SPRING_PROFILES_ACTIVE
                value: "dev"
            ports:
              - containerPort: 5000
              - containerPort: 9090
            livenessProbe:
              httpGet:
                path: /actuator/health
                port: 9090
              initialDelaySeconds: 120
              periodSeconds: 60
              timeoutSeconds: 10
              successThreshold: 1
              failureThreshold: 2
            readinessProbe:
              httpGet:
                path: /actuator/health
                port: 9090
              initialDelaySeconds: 120
              periodSeconds: 10
              timeoutSeconds: 10
