apiVersion: v1
kind: Service
metadata: 
  name: svc-server--discovery-stack
  namespace: shoes-eks
spec:
  type: LoadBalancer
  selector:
      app: server--discovery-stack
  ports:
    - port: 8762
      name: http-8762
      protocol: TCP
      targetPort: 8762
    - port: 9190
      name: http-prometheus
      protocol: TCP
      targetPort: 9190