apiVersion: v1
kind: Service
metadata: 
  name: svc-server--discovery-stack
  namespace: shoes-eks
spec:
  type: ClusterIP
  selector:
      app: server--discovery-stack
  ports:
    - port: 5000
      name: http-5000
      protocol: TCP
      targetPort: 5000
    - port: 9090
      name: http-prometheus
      protocol: TCP
      targetPort: 9090